---
- name: Include facts
  include_tasks: facts.yml

- name: (Ubuntu) Update APT cache
  apt:
    force_apt_get: true
    cache_valid_time: "3600"
    state: present
    update_cache: true
  when: ansible_distribution == "Ubuntu"

- name: Install Apache packages
  package:
    name: "{{ apache_packages }}"
    state: present

- name: Delete Apache "hello world" configuration
  file:
    path:
    state: absent
  notify:
    - restart apache
  with_items:
    - "{{ apache_config_site_path }}/autoindex.conf"
    - "{{ apache_config_site_path }}/welcome.conf"

- name: Ensure Apache group exists
  group:
    name: "{{ apache_user }}"
    state: present

- name: Ensure Apache user exists
  user:
    name: "{{ apache_user }}"
    state: present
    group: "{{ apache_group }}"

- name: Configure Apache
  include_tasks: "configure/main.yml"

- name: Include systemd restart configuration
  include: systemd.yml
  when: >-
    ( apache_systemd_restart|default(False)
    or systemd_restart|default(False) )
    and systemd_restart_setting is defined  

- name: Start and enable Apache service
  service:
    name: "{{ apache_daemon }}"
    state: started
    enabled: true
