---
- name: (RedHat) Bind Apache to specified HTTP port
  lineinfile:
    path: "{{ apache_config }}"
    regexp: "^Listen 80$"
    line: "Listen {{ apache_port_http }}"
  when: ansible_os_family|lower == "redhat"

- name: (RedHat) Bind Apache to specified HTTPS port
  lineinfile:
    path: "{{ apache_config_ports }}"
    regexp: "^Listen 443 https$"
    line: "Listen {{ apache_port_https }} https"
  when: ansible_os_family|lower == "redhat"
